name: fluffychat
description: Chat with your friends.
publish_to: none
version: 1.0.1+2


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  adaptive_dialog: ^1.9.0-no-macos.2
  animations: ^2.0.7
  badges: ^2.0.3
  blurhash_dart: ^1.1.0
  callkeep: ^0.3.2
  chewie: ^1.3.6
  collection: ^1.16.0
  connectivity_plus: ^3.0.2
  animate_gradient: ^0.0.2+1
  cupertino_icons: any
  desktop_drop: ^0.4.0
  desktop_lifecycle: ^0.1.0
  desktop_notifications: ^0.6.3
  device_info_plus: ^8.0.0
  dynamic_color: ^1.6.0
  emoji_picker_flutter: ^1.5.1
  emoji_proposal: ^0.0.1
  emojis: ^0.9.9
  file_picker: ^5.3.0
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_app_lock: ^3.0.0
  flutter_blurhash: ^0.7.0
  flutter_cache_manager: ^3.3.0
  dio_cache_interceptor: ^3.4.2
  flutter_foreground_task: ^3.10.0
  flutter_highlighter: ^0.1.1
  flutter_html: ^3.0.0-beta.2
  flutter_html_table: ^3.0.0-beta.2
  flutter_linkify: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^3.1.0
  flutter_math_fork: ^0.7.1
  flutter_olm: ^1.2.0
  flutter_openssl_crypto: ^0.1.0
  flutter_ringtone_player: ^3.1.1
  flutter_secure_storage: ^7.0.1
  flutter_typeahead:
    git:
      url: https://github.com/wtosborne03/flutter_typeahead.git
  flutter_web_auth_2: ^2.1.1
  flutter_webrtc: ^0.9.30+hotfix.2
  future_loading_dialog: ^0.2.3
  geolocator: ^7.6.2
  handy_window: ^0.1.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.4
  image_picker: ^0.8.4+8
  intl: any
  floating_bubbles: ^2.5.1
  just_audio: ^0.9.30
  just_audio_mpv: ^0.1.6
  awesome_notifications: ^0.7.4+1
  keyboard_shortcuts: ^0.1.4
  latlong2: ^0.8.1
  linkify: ^5.0.0
  matrix: ^0.22.2
  matrix_homeserver_recommendations: ^0.3.0
  native_imaging: ^0.1.0
  package_info_plus: ^4.0.0
  path_provider: ^2.0.9
  dio: ^5.2.1+1
  permission_handler: ^10.0.0
  pin_code_text_field: ^1.8.0
  provider: ^6.0.2
  punycode: ^1.0.0
  qr_code_scanner: ^1.0.0
  qr_flutter: ^4.0.0
  receive_sharing_intent: ^1.4.5
  record: ^4.4.4
  scroll_to_index: ^3.0.1
  share_plus: ^7.0.0
  shared_preferences: 2.0.15 # Pinned because https://github.com/flutter/flutter/issues/118401
  slugify: ^2.0.0
  firebase_core: ^2.15.0
  swipe_to_action: ^0.2.0
  tor_detector_web: ^1.1.0
  uni_links: ^0.5.1
  unifiedpush: ^4.0.3
  universal_html: ^2.0.8
  web_socket_channel: ^2.4.0
  url_launcher: ^6.0.20
  vibration: ^1.7.4-nullsafety.0
  video_compress: ^3.1.1
  google_fonts: ^5.1.0
  firebase_messaging: ^14.6.5
  video_player: ^2.2.18
  vrouter: ^1.2.0+21
  webrtc_interface: ^1.0.13

dev_dependencies:
  hive_generator: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.0.3+1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  icons_launcher: ^2.1.1
  integration_test:
    sdk: flutter
  msix: ^3.6.2
  build_runner: ^2.4.6
  translations_cleaner: ^0.0.5

icons_launcher:
  image_path: "assets/appicon.png"
  platforms:
    android:
      enable: true
      adaptive_background_image: "assets/appicon_background.png"
      adaptive_monochrome_image: "assets/appicon_foreground.png"
      adaptive_foreground_image: "assets/appicon_foreground.png"
    ios:
      enable: true
    web:
      enable: true
    macos:
      enable: true

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: "assets/info-logo.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/
    - assets/js/
    - assets/js/package/
    - assets/colleges/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: RobotoMono
      fonts:
        - asset: fonts/Roboto/RobotoMono-Regular.ttf



msix_config:
  display_name: FluffyChat
  publisher_display_name: FluffyChat
  publisher: CN=FluffyChat, O=Head of bad integration tests, L=Matrix, S=Internet, C=EU
  identity_name: com.coursebubble,chat
  logo_path: assets\logo.png
  capabilities: internetClient, location, microphone, webcam
  protocol_activation: https
  app_uri_handler_hosts: coursebubble, matrix.to
  execution_alias: coursebubble
  sign_msix: false
  install_certificate: false

dependency_overrides:
  http: ^1.1.0
  intl: any
  # fake secure storage plugin for Windows
  # See: https://gitlab.com/gitlab-com/gl-infra/reliability/-/issues/15161
  flutter_secure_storage_windows:
    git:
      url: https://gitlab.com/TheOneWithTheBraid/flutter_secure_storage_windows.git
      ref: main
  flutter_webrtc:
    git: https://github.com/krille-chan/flutter-webrtc.git
  geolocator_android:
    hosted:
      name: geolocator_android
      url: https://hanntech-gmbh.gitlab.io/free2pass/flutter-geolocator-floss
  # waiting for null safety
  # Upstream pull request: https://github.com/AntoineMarcel/keyboard_shortcuts/pull/13
  keyboard_shortcuts:
    git:
      url: https://github.com/TheOneWithTheBraid/keyboard_shortcuts.git
      ref: null-safety
