// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhDTVEXo0hbCRog2NwfoB6SoeiOvDpTdc',
    appId: '1:867948555298:web:118f2d90d94a257f0f6e7b',
    messagingSenderId: '867948555298',
    projectId: 'coursebubble-247b2',
    authDomain: 'coursebubble-247b2.firebaseapp.com',
    storageBucket: 'coursebubble-247b2.appspot.com',
    measurementId: 'G-2S3M3GSH8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8IHrtUUiFP6DYbA88lWUIkNY6wLD1gYE',
    appId: '1:867948555298:android:83df4a3a0812b2eb0f6e7b',
    messagingSenderId: '867948555298',
    projectId: 'coursebubble-247b2',
    storageBucket: 'coursebubble-247b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4X2Sv7t6JZnK3mTmLricG3NBz-VHXq7s',
    appId: '1:867948555298:ios:49f5738c02f9a11e0f6e7b',
    messagingSenderId: '867948555298',
    projectId: 'coursebubble-247b2',
    storageBucket: 'coursebubble-247b2.appspot.com',
    iosClientId:
        '867948555298-mdd4e84d65dvnqqju7sf7no9p78m1r0d.apps.googleusercontent.com',
    iosBundleId: 'com.coursebubble.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4X2Sv7t6JZnK3mTmLricG3NBz-VHXq7s',
    appId: '1:867948555298:ios:57fefb4efd713a580f6e7b',
    messagingSenderId: '867948555298',
    projectId: 'coursebubble-247b2',
    storageBucket: 'coursebubble-247b2.appspot.com',
    iosClientId:
        '867948555298-6jcrk23ol5tffpqs1r5rribs8gfd4ico.apps.googleusercontent.com',
    iosBundleId: 'com.coursebubble.chat',
  );
}
